sudo: required
services:
  - docker

before_install:
  - docker build -t dennisdurairaj/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run dennisdurairaj/react-test /bin/sh -c "CI=true npm run test"

after_success:
  - docker build -t dennisdurairaj/multi-client ./client
  - docker build -t dennisdurairaj/multi-nginx ./nginx
  - docker build -t dennisdurairaj/multi-server ./server
  - docker build -t dennisdurairaj/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push dennisdurairaj/multi-client
  - docker push dennisdurairaj/multi-nginx
  - docker push dennisdurairaj/multi-server
  - docker push dennisdurairaj/multi-worker
